version: "4"

services: 

  php-fpm:
    image: php:8.1-fpm-alpine
    container_name: php-fpm
    ports:
      - 9000
    volumes:
      - ./www:/var/www
      - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf
  nginx-alpine:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - 8082:80
    #networks: 
    #  - gmb-bridge
    environment:
      - TZ=Asia/Jakarta
    volumes: 
      - ./www:/var/www
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
